name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  release:
    types:
      - created

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.77.2
          components: clippy, rustfmt
      - run: make init
      - run: make lint
      - run: make test
